#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Category
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NAME = 1
  PARENT_CATEGORY = 2

  FIELDS = {
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    PARENT_CATEGORY => {:type => ::Thrift::Types::STRUCT, :name => 'parent_category', :class => ::Category}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Product
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NAME = 1
  STOCK = 2
  CATEGORY = 3

  FIELDS = {
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    STOCK => {:type => ::Thrift::Types::I32, :name => 'stock'},
    CATEGORY => {:type => ::Thrift::Types::STRUCT, :name => 'category', :class => ::Category}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class OrderItem
  include ::Thrift::Struct, ::Thrift::Struct_Union
  PRODUCT = 1
  AMOUNT = 2
  ID = 3

  FIELDS = {
    PRODUCT => {:type => ::Thrift::Types::STRUCT, :name => 'product', :class => ::Product},
    AMOUNT => {:type => ::Thrift::Types::I32, :name => 'amount'},
    ID => {:type => ::Thrift::Types::I32, :name => 'id'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Cart
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ORDER_ITEMS = 1

  FIELDS = {
    ORDER_ITEMS => {:type => ::Thrift::Types::LIST, :name => 'order_items', :element => {:type => ::Thrift::Types::STRUCT, :class => ::OrderItem}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class AmountExceeded < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

